#!/bin/bash -xe

#prep_sample.sge
#sge submission script to prepare sequencing reads for SNP calling
#M. Supple
#31 March 2015

#usage  
#qsub prep_reads.sge <infile.fq>
	#<infile.fq>:  an interleaved fastq file  


#sge submission info
#$ -N prep
#$ -o prep.output
#$ -l virtual_free=1.8g,h_vmem=1.9g
#$ -cwd
#$ -j y



#print some sge info
echo Job $JOB_NAME started `date` in queue $QUEUE with id=$JOB_ID on `hostname`
echo input file is $1

#set path for python virtual environment
path=~/.virtualenvs/gbstrim/bin

#remove adapter contamination with gbstrim
$path/python $path/gbstrim.py -e CTGCAG -d dimers.txt $1 > tmp_clean.fastq

#merge ovelapping reads with flash and merge combined and uncombined reads
~/programs/FLASH-1.2.11/flash -M 70 -I tmp_clean.fastq
cat out.notCombined.fastq out.extendedFrags.fastq > tmp_cleanmerge.fastq

#quality filter with sickle
sickle se -x -g -f tmp_cleanmerge.fastq -t sanger -o sample.fastq.gz

#quality check with fastqc
#fastqc sample.fastq.gz

#print note that job completed
echo done `date`


