#!/bin/bash

#prep_gbs_denovo.sge
#sge submission script to finish preparing reads for denovo assembly
#M. Supple
#last modified 13 July 2016

#usage
#qsub prep_gbs_denovo.sge <prep.input>
#<prep.input>:  see prep.example.input or example at end of this script

#requires
#seqtk
#process_radtags (Stacks)

#output
#single fastq (interleaved, but pairs not maintained) for each sample hard trimmed to specified length



#sge submission info
#$ -N prep_gbs_denovo
#$ -o prep_gbs_denovo.output
#$ -cwd
#$ -j y



#print some sge info
echo Job $JOB_NAME started `date` in queue $QUEUE with id=$JOB_ID on `hostname`

#read in the input file
source $1


#make output directory for trimmed files
mkdir $gbs_path/$user/$lane_name/qc_trimmed$trimlen
mkdir tempseqs

#get file info
pathfiles="$gbs_path/$user/$lane_name/qc/qc_S*_il.fastq.gz"

#process if file > 100000, remove 1bp reads, print to temp directory
for fullfile in $( ls $pathfiles ); do
	filename=$(basename "$fullfile")
	filesize=$( stat -c%s $fullfile )
	if [ "$filesize" -gt "200000" ]; then
		#get rid of reads that are just 1 N (they are for maintaining pairs, removing gives better downstream info on improper restriction sites)
		gunzip -c $fullfile | seqtk seq -L 2 | gzip > tempseqs/trim_$filename		
	else echo "$filename failed"
	fi
done

#remove reads without proper restriction site and hard trim so all reads are the same specified length
process_radtags -p tempseqs/ -e pstI -i gzfastq -t $trimlen -o $gbs_path/$user/$lane_name/qc_trimmed$trimlen
	#I interleaved
	#t trim length

#remove files that are too small
for fullfile in $( ls $gbs_path/$user/$lane_name/qc_trimmed$trimlen/trim_qc_S*_il.fq.gz ); do
	filesize=$( stat -c%s $fullfile )
	if [ "$filesize" -lt "200000" ]; then
		rm $fullfile
		echo "$(basename "$fullfile") failed"
	fi
done

rm -rf tempseqs/

#print note that job completed
echo done `date`

##sequencing and sample information
#lane_name=LANE_NAME
##user group for output
#user=Eucalyptus	
#path to data
#gbs_path="/borevitz/gbs/samples/"
##trim length for denovo
#trimlen=<64>
