#!/bin/bash
set -xe 

#sge submission info
#$ -N prep
#$ -o prep_gbs.output
#$ -pe threads 11
#$ -l virtual_free=1.8g,h_vmem=1.9g
#$ -cwd
#$ -j y


#print some sge info
echo Job $JOB_NAME started `date` in queue $QUEUE with id=$JOB_ID on `hostname`

#read the input file
source $1

#make output directory for trimmed files
mkdir trimmed

#cut all reads to 64 bases
pathfiles="/borevitz/gbs/samples/$user/$lane_name/qc/qc_S*_il.fastq.gz"
for fullfile in $( ls $pathfiles ); do
	filename=$(basename "$fullfile")
	filesize=$( stat -c%s $fullfile )
	if [ "$filesize" -gt "100000" ]; then
		gunzip -c $fullfile | ~/programs/bin/fastx_trimmer -Q 33 -l 64 -i -z -o trimmed/trim_$filename
	else echo "$filename failed"
	fi
done


#print note that job completed
echo done `date`


##example input file for qc and prepping reads
#
##input fastq files
#file1=/PATH/TO/FASTQ/FILE/sample_R1_001.fastq.gz
#file2=/PATH/TO/FASTQ/FILE/sample_R2_001.fastq.gz
#
#fastqc params
#fastqc_outdir=/PATH/TO/DIR/FOR/OUTPUT
#
##sequencing and sample information
#lane_name=LANE_NAME
#barcode_file=LANE_BARCODES.tab
#
##user group for output
#user=Eucalyptus
#
##number of threads to use
#threads=11
